### Creates a new patient entity
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
  "name": "john Kafka",
  "email": "johnKafka@email.com",
  "address": "2 hong road",
  "dateOfBirth": "1997-03-07",
  "registeredDate": "2025-06-12"
}

###